name: Build
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        # include:
        #   - os: [self-hosted, ARM64]
        #   - os: [self-hosted, ARMHF]
    name: Make
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ contains(matrix.os, 'self-hosted') }}
    steps:
    - name: Set up Go.
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
      id: go
    - name: Install Linux-specific packages
      run: "sudo apt install -y webkit2gtk-4.0"
      if: ${{ contains(matrix.os, 'ubuntu-latest') }}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      run: go build .
